#!/bin/bash

echo ""
echo "                                   -------------"
echo "                                   !!!WARNING!!!"
echo "                                   -------------"
echo ""
if [ -n "$SUDO_USER" ] && [ "$SUDO_USER" != "root" ]; then
  echo "Adding user $SUDO_USER to 'dialout' group to enable flash procedure..."
  echo "You'll need to reboot your system to enable changes"
  usermod -a -G dialout "$SUDO_USER"
elif [ -n "$USER" ] && [ "$USER" != "root" ]; then
  echo "Adding user $USER to 'dialout' group to enable flash procedure..."
  echo "You'll need to reboot your system to enable changes"
  usermod -a -G dialout "$USER"
fi
echo ""
echo ""
